language: ruby
cache: bundler
before_script: "./bin/ci/before_build"
script: "bundle exec rspec -c spec"
rvm:
  - jruby-9.1.8.0
notifications:
  recipients:
    - michael@rabbitmq.com

services:
  - rabbitmq

branches:
  only:
    - master
